name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.0'
          host: 'windows'
          target: 'desktop'
          modules: 'qttools5'
          install-deps: 'true'

      - name: Build
        shell: powershell
        id: build
        env:
          BOOST_ROOT: ${{ env.BOOST_ROOT }}
        run: |
          $build_folder = "build"
          $krb_ver = "${{ github.ref }}" -replace '[refs/tags/]'
          $release_name = "KarboLite-wallet-win64-$krb_ver"
          set CMAKE_PREFIX_PATH="$($qt5_cmake)"
          $qt5_cmake = "${{ env.Qt5_Dir }}/lib/cmake" -replace '[/]', '\\'
          Remove-Item cryptonote -Recurse -ErrorAction Ignore
          git clone https://github.com/seredat/karbowanec cryptonote
          mkdir "$build_folder"
          cd "$build_folder"
          Start-Process cmake -ArgumentList "-G ""Visual Studio 16 2019"" -A x64",".." -NoNewWindow -Wait
          Start-Process msbuild -ArgumentList "KarboLite.sln","/p:Configuration=Release" -NoNewWindow -Wait
          $build_path = "./$build_folder"
          echo "::set-output name=build_path::${build_path}"
          echo "::set-output name=release_name::${release_name}"
          echo "::set-output name=krb_ver::${krb_ver}"
  
      - name: Pack
        shell: powershell
        id: pack
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\'
        run: |
          $build_folder = "${{ steps.build.outputs.build_path }}"
          $release_name = "${{ steps.build.outputs.release_name }}"
          $release_folder = "Release"
          cd "$build_folder"
          $krb_ver = "${{ steps.build.outputs.krb_ver }}"
          mkdir "$release_folder/$release_name"
          cd "$release_folder"
          cp KarboLite.exe "$release_name/"
          cp "../../LICENSE" "$release_name/LICENSE.txt"
          windeployqt --release KarboLite.exe --dir "$release_name/"
          Compress-Archive -Path "$release_name/" -DestinationPath "$release_name.zip"
          $sha256 = (Get-FileHash "$release_name.zip").Hash
          $asset_path = "./$build_folder/$release_folder/$release_name.zip"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=krb_ver::${krb_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.pack.outputs.asset_path }}
          name: Karbo Wallet ${{ steps.pack.outputs.krb_ver }}
          body: |
            **${{ steps.pack.outputs.release_name }}**
            ${{ steps.pack.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.0'
          modules: 'qttools5'
          install-deps: 'true'

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          krb_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="KarboLite-wallet-macOS-$krb_ver"
          app_name="KarboLite.app"
          brew install gcc boost@1.60
          brew link boost@1.60 --force
          rm -rf cryptonote
          git clone https://github.com/seredat/karbowanec.git cryptonote
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -DCMAKE_C_FLAGS="-mmacosx-version-min=10.12" -DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.12" -D CMAKE_BUILD_TYPE=Release ../..
          make
          macdeployqt "$app_name"
          cpack
          mv *.dmg "$release_name".dmg
          sha256=$(shasum -a 256 "$release_name".dmg | awk '{ print toupper($1) }')
          asset_path="./$build_folder/$release_name.dmg"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=krb_ver::${krb_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Karbo Wallet ${{ steps.build.outputs.krb_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu16:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          BOOST_ROOT=
          sudo apt update -y
          sudo apt install -y qt5-default qttools5-dev qttools5-dev-tools libboost-all-dev
          build_folder="build/release"
          krb_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=KarboLite-ubuntu16.04-"$krb_ver"
          app_name="KarboLite"
          rm -rf cryptonote
          git clone https://github.com/seredat/karbowanec.git cryptonote
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake ../..
          make
          tar -czf "$release_name".tar.gz "$app_name"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name".tar.gz
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=krb_ver::${krb_ver}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Karbo Wallet ${{ steps.build.outputs.krb_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          BOOST_ROOT=
          sudo apt update -y
          sudo apt install -y qt5-default qttools5-dev qttools5-dev-tools libboost-all-dev
          build_folder="build/release"
          krb_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=KarboLite-ubuntu-18.04-"$krb_ver"
          app_name="KarboLite"
          rm -rf cryptonote
          git clone https://github.com/seredat/karbowanec.git cryptonote
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake ../..
          make
          tar -czf "$release_name".tar.gz "$app_name"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name".tar.gz
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=krb_ver::${krb_ver}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Karbo Wallet ${{ steps.build.outputs.krb_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

